export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const manufacturerLogos: Record<string, string> = {
  Acura: "https://img.icons8.com/color/48/acura.png",
  "Alfa Romeo": "https://img.icons8.com/color/48/alfa-romeo.png",
  "Aston Martin": "https://img.icons8.com/color/48/aston-martin.png",
  Audi: "https://img.icons8.com/color/48/audi.png",
  Bentley: "https://img.icons8.com/color/48/bentley.png",
  BMW: "https://img.icons8.com/color/48/bmw.png",
  Buick: "https://img.icons8.com/color/48/buick.png",
  Cadillac: "https://img.icons8.com/color/48/cadillac.png",
  Chevrolet: "https://img.icons8.com/color/48/chevrolet.png",
  Chrysler: "https://img.icons8.com/color/48/chrysler.png",
  Citroen: "https://img.icons8.com/color/48/citroen.png",
  Dodge: "https://img.icons8.com/color/48/dodge.png",
  // Ferrari: "https://img.icons8.com/color/48/ferrari.png",
  Ferrari: "https://img.icons8.com/?size=96&id=36720&format=png",
  Fiat: "https://img.icons8.com/color/48/fiat.png",
  Ford: "https://img.icons8.com/color/48/ford.png",
  GMC: "https://img.icons8.com/color/48/gmc.png",
  Honda: "https://img.icons8.com/color/48/honda.png",
  Hyundai: "https://img.icons8.com/color/48/hyundai.png",
  // Infiniti: "https://img.icons8.com/color/48/infiniti.png",
  Infiniti: "https://cdn.worldvectorlogo.com/logos/infiniti-logo-1.svg",
  Jaguar: "https://img.icons8.com/?size=96&id=59014&format=png",
  Jeep: "https://img.icons8.com/color/48/jeep.png",
  Kia: "https://img.icons8.com/color/48/kia.png",
  Lamborghini: "https://img.icons8.com/color/48/lamborghini.png",
  "Land Rover": "https://img.icons8.com/color/48/land-rover.png",
  Lexus: "https://img.icons8.com/color/48/lexus.png",
  Lincoln: "https://img.icons8.com/color/48/lincoln.png",
  Maserati: "https://img.icons8.com/color/48/maserati.png",
  Mazda: "https://img.icons8.com/color/48/mazda.png",
  McLaren: "https://img.icons8.com/color/48/mclaren.png",
  "Mercedes-Benz": "https://img.icons8.com/color/48/mercedes-benz.png",
  MINI: "https://img.icons8.com/color/48/mini-cooper.png",
  Mitsubishi: "https://img.icons8.com/color/48/mitsubishi.png",
  Nissan: "https://img.icons8.com/color/48/nissan.png",
  Porsche: "https://img.icons8.com/color/48/porsche.png",
  Ram: "https://img.icons8.com/color/48/ram.png",
  "Rolls-Royce": "https://img.icons8.com/color/48/rolls-royce.png",
  Subaru: "https://img.icons8.com/color/48/subaru.png",
  Tesla: "https://img.icons8.com/?size=160&id=aTi1yYs3Jt5n&format=png",
  Toyota: "https://img.icons8.com/color/48/toyota.png",
  Volkswagen: "https://img.icons8.com/color/48/volkswagen.png",
  Volvo: "https://img.icons8.com/color/48/volvo.png",
};

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
